### ISSUE TITLE
Why the boost::geometry::box cannot be showed in my vs community 2019 

### ISSUE THREAD

**Issue by zhumeng-robotics** [awulkiew/graphical-debugging#38] opened 2021-07-08 01:58 UTC
Hi, 
I am a new user for the graphical-debugging, I found the boost::geometry::box cannot be showed in vs community 2019. is there some setting to enable this plot ?

![Screenshot 2021-07-08 095742](https://user-images.githubusercontent.com/10232971/124850304-fc108780-dfd2-11eb-863b-66bd87f0eeef.png)

**Comment by awulkiew** [comment] 2021-07-08 08:59
Hi, All of the supported geometries should be shown. What are the coordinates of the box you're trying to display?

**Comment by zhumeng-robotics** [comment] 2021-07-09 05:28
> Hi, All of the supported geometries should be shown. What are the coordinates of the box you're trying to display?

Hi Adam, 
The qbox position info is as below, it is the return_envelope of qpoly. I am also feel strange since the box is the base type of boost geometry...
![Screenshot 2021-07-09 132555](https://user-images.githubusercontent.com/10232971/125027702-3bb19f00-e0b9-11eb-8167-6ab37ba3058b.png)

**Comment by awulkiew** [comment] 2021-07-09 10:40
Thanks! I see that the colors are not in order, this means you have created the list by adding some geometries and then removing some of them and adding again. This is fine. I only want to know if the problem is related to the drawing of the box or to the list manipulation. Was the box visible at some point and then disappear? Is it shown if you create a list in a different order? Is it shown if it's the only geometry that is on the list? Etc.

**Comment by awulkiew** [comment] 2023-05-18 21:44
It should be fixed in v0.34.

**Closed** 2023-05-18 21:44 UTC
Labels: bug
