### ISSUE TITLE
Add support for MSVS 22

### ISSUE THREAD

**Issue by TrackerSB** [awulkiew/graphical-debugging#50] opened 2022-09-07 13:45 UTC
The plugin is not allowed to be installed in Visual Studio 2022.

**Comment by mloskot** [comment] 2022-09-08 07:19
Use the Search next time.
This is duplicate of https://github.com/awulkiew/graphical-debugging/issues/44

**Comment by awulkiew** [comment] 2023-05-18 21:42
I've created VS2022-only release. You can dowload it here:
https://github.com/awulkiew/graphical-debugging/releases/tag/v0.50
Please let me know if everything works for you.

**Closed** 2023-05-28 13:04 UTC
Labels: enhancement
